import { Geist, Geist_Mono, Roboto } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import { Toaster } from "react-hot-toast";
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
export const metadata = {
  title: "Book Your Tickets  ",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {

  return (
    <ClerkProvider>

      <html lang="en">
        <head>
        <link rel="icon" type="image/svg+xml" href="/favicon.svg" />
        </head>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col`}
        >
          
          <Toaster />
          <Navbar />
          <main className="mt-10 md:mt-14">
            
            {children}
          </main>
          <Footer />
        </body>
      </html>
    </ClerkProvider>
  );
}
